version: '3.8'

services:
  agoricocw:
    build:
      context: .
      dockerfile: Dockerfile
    stop_signal: SIGTERM
    stop_grace_period: 30s
    restart: always
    logging:
      driver: journald
    ports:
      - "3011:3011"
    environment:
      - NODE_ENV=production
    volumes:
      - "./binaries/agd:/usr/local/bin/agd"
      - "~/.agoric:/root/.agoric"
    command: ["node_modules/.bin/tsx", "./src/index.ts"]
