version: '3.8'

services:
  verifier:
    image: ghcr.io/sigstore/cosign/cosign:v2.4.1
    entrypoint: ["cosign"]
    command: [
      "verify",
      "--key",
      "/keys/cosign.pub",
      "simplystaking/agoric-fast-usdc-ocw:v0.0.4"
    ]
    volumes:
      - ./keys:/keys
  agoricocw:
    depends_on:
      - verifier
    build:
      context: .
      dockerfile: Dockerfile
    stop_signal: SIGTERM
    stop_grace_period: 30s
    restart: always
    logging:
      driver: "json-file"
    labels:
      logging: "promtail"
    ports:
      - "3011:3011"
    environment:
      - NODE_ENV=production
    volumes:
      - "./binaries/agd:/usr/local/bin/agd"
      - "~/.agoric:/app/.agoric"
      - "./.env:/app/.env"
    command: ["node_modules/.bin/tsx", "./src/index.ts"]
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Access Docker logs
      - ./promtail-config.yml:/etc/promtail/promtail.yml  # Promtail config
      - ./promtail/positions.yaml:/tmp/positions.yaml  # Store positions
    command:
      - -config.file=/etc/promtail/promtail.yml