{
 "title": "Agoric OCW Template",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d" }
  ]
 },
 "panels": [
  {
   "title": "Watchers",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# DSRV: agoric17crpkfxarq658e9ddru2petrfr0fhjzvjfccq9\n# 01Node: agoric1ym488t6j24x3ys3va3452ftx44lhs64rz8pu7h\n# Simply Staking: agoric1s5yawjgj6xcw4ea5r2x4cjrnkprmd0fcun2tyk"
   }
  },
  { "title": "Agoric CCTP TXs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CCTP Burn Events",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "targets": [
    { "expr": "events_count{}", "legendFormat": "{{network}}" }
   ]
  },
  {
   "title": "Grouped CCTP Burn Events",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "targets": [
    { "expr": "events_count{}", "legendFormat": "{{job}} {{network}}" }
   ]
  },
  {
   "title": "CCTP Total amount",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "targets": [
    { "expr": "total_amount{}", "legendFormat": "{{network}}" }
   ]
  },
  {
   "title": "CCTP Burn Events in the last $interval",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "increase(events_count{}[$interval])",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Grouped CCTP Burn Events in the last $interval",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "increase(events_count[$interval]) > 0",
     "legendFormat": "{{network}} {{ job }}"
    }
   ]
  },
  {
   "title": "CCTP Total Amount in the last $interval",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "increase(total_amount{}[$interval])",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Last Watcher Offer",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "targets": [
    { "expr": "last_watcher_offer{}", "legendFormat": "{{watcher}}" }
   ]
  },
  {
   "title": "CCTP Reverted TXs in the last $interval",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "increase(reverted_tx_count{}[$interval])",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Missed Worker NFA",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "targets": [
    { "expr": "worker_missed_nfa", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Failed submissions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "targets": [
    { "expr": "submission_errors", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Current Block Window Amount",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
   "targets": [
    { "expr": "current_block_range_amount{}", "legendFormat": "{{network}}" }
   ]
  },
  { "title": "RPCs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "RPC Health",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rpc_alive{}", "legendFormat": "{{network}}" }
   ]
  },
  {
   "title": "RPC Block Height",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "targets": [
    { "expr": "rpc_height{}", "legendFormat": "{{network}}" }
   ]
  },
  {
   "title": "RPC Block Height increase in the last $interval",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "increase(rpc_height{}[$interval])",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Agoric Active RPC",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "agoric_active_rpc{} == 1", "legendFormat": "{{endpoint}}" }
   ]
  }
 ]
}